services:
  - type: web
    name: election-whatsapp-crm
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: DEFAULT_COUNTRY_CODE
        value: "91"
      - key: DATABASE_URL
        sync: false
      - key: MIN_DELAY_MS
        value: "20000"
      - key: MAX_DELAY_MS
        value: "35000"
      - key: WARMUP_SEND_COUNT
        value: "15"
      - key: WARMUP_MIN_DELAY_MS
        value: "45000"
      - key: WARMUP_MAX_DELAY_MS
        value: "60000"
      - key: BATCH_SIZE
        value: "50"
      - key: BATCH_PAUSE_MS
        value: "900000"
      - key: DAILY_MAX_MSG
        value: "600"
      - key: LOG_LEVEL
        value: "silent"
      - key: JWT_SECRET
        value: "CHANGE_ME_TO_A_RANDOM_STRING"
      - key: FREE_CREDITS
        value: "50"
      - key: PRICE_PER_MSG
        value: "0.4"
      - key: MIN_QTY
        value: "100"
      - key: MAX_QTY
        value: "1000"
      - key: ADMIN_EMAIL
        value: "piyushbhuyan71@gmail.com"
      - key: UPI_ID
        value: "9864854881@ptsbi"
      - key: UPI_NAME
        value: "Piyush Bhuyan"
      - key: ADMIN_WHATSAPP
        value: "9864854881"
